import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  concepts: [
    {
    type: 'category',
    label: 'Introduction',
    collapsed: false,
    collapsible: false,
    link: {
    type: "doc",
    id: "mantis",
    },
    items: [
    { type: "autogenerated", dirName: "concepts" }
    ],
    },
    ],

  rollup: [

    {
      type: 'category',
      label: 'Rollup',
      collapsed: false,
      collapsible: false,
      items: [
        {type: "autogenerated", dirName: 'rollup'}
      ],
    },
  ],

  protocol: [ 
    {
      type: 'category',
      label: 'Protocol',
      collapsed: false,
      collapsible: false,
      items: [
        {type: "autogenerated", dirName: 'protocol'}
      ],
    },
  ],
  solvers: [

    {
      type: 'category',
      label: 'Solvers',
      collapsed: false,
      collapsible: false,
      items: [
        {type: "autogenerated", dirName: 'solvers'}
      ],
    },
  ],


  user_guides: [
    {type: "autogenerated", dirName: 'user_guides'}
  ]
};

export default sidebars;
